/**
 * ⚠️ DEPRECATED: This file is no longer used
 *
 * We now use LAZY PROVISIONING via the `authenticatedUserWithOrg` fixture
 * in tests/e2e/fixtures/test-fixtures.ts
 *
 * This provides several benefits:
 * 1. No global setup dependency - tests are self-healing
 * 2. Tests can be run individually without running setup first
 * 3. Database can be wiped and tests will recreate what they need
 * 4. Faster test execution - no waiting for global setup
 *
 * To migrate your tests:
 * - Use `test` from '@/tests/e2e/fixtures/test-fixtures'
 * - Request `authenticatedUserWithOrg` in your test parameters
 * - The fixture will ensure the user + org exist before running
 *
 * This file is kept for reference only and can be safely deleted.
 */

import { test as setup } from '@playwright/test';
import path from 'path';
import { fileURLToPath } from 'url';
import { getUserIdByEmail, getOrgIdByUserId } from './utils/db-utils';
import { cleanupAllTestUsers } from './utils/test-cleanup';
import {
  createUserWithOrgAndState,
  savePlaywrightAuthState,
  signInUser,
  createAuthenticatedUser,
} from './utils/auth-factories';
import {
  createTestOrganization,
  createTestGroup,
  addUserToOrganization,
  addUserToGroup,
} from './utils/test-factories';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const authFile = path.join(__dirname, '../../playwright/.auth/admin.json');

/**
 * @deprecated Use authenticatedUserWithOrg fixture instead
 *
 * Global setup that runs once before all tests.
 *
 * New approach using direct database calls instead of UI:
 * 1. Clean up all test data from previous runs (except admin user)
 * 2. Check if admin user exists in database
 * 3. If not, create user + org using Supabase Auth API + direct DB calls
 * 4. If yes but no org, create org using direct DB calls
 * 5. Sign in and save auth state for tests to reuse
 *
 * This is 10-100x faster than the old UI-based approach and more reliable.
 */
setup('authenticate admin user and create org', async () => {
  const email = process.env.TEST_ADMIN_EMAIL;
  const password = process.env.TEST_ADMIN_PASSWORD;
  const fullName = 'Admin Test User';
  const orgName = 'Test Organization';

  if (!email || !password) {
    throw new Error('TEST_ADMIN_EMAIL and TEST_ADMIN_PASSWORD must be set in .env.test');
  }

  // Clean up all test data from previous runs (except admin user)
  console.log('\n🧹 Cleaning up test data from previous runs...');
  try {
    const cleanupResult = await cleanupAllTestUsers(
      'test.%@example.com', // Pattern matches all test emails generated by factories
      [email], // Preserve admin user
      true // verbose
    );

    if (cleanupResult.success) {
      const total = Object.values(cleanupResult.deletedCounts).reduce((a, b) => a + b, 0);
      console.log(`✅ Cleaned up ${total} items from previous runs`);
    } else {
      console.warn('⚠️  Cleanup had some errors:', cleanupResult.errors);
    }
  } catch (error) {
    console.warn('⚠️  Cleanup failed, but continuing with setup:', (error as Error).message);
  }

  console.log(`\n🔐 Setting up authentication for admin user: ${email}`);

  // Check if user exists in database
  let userId: string | null = null;
  let orgId: string | null = null;

  try {
    userId = await getUserIdByEmail(email);
    console.log(`✅ User exists in database (ID: ${userId})`);

    try {
      orgId = await getOrgIdByUserId(userId);
      console.log(`✅ User already has an organization (ID: ${orgId})`);
    } catch (error) {
      console.log('ℹ️  User exists but has no organization yet');
    }
  } catch (error) {
    console.log('ℹ️  User does not exist in database yet');
  }

  // Scenario 1: User doesn't exist - create everything
  if (!userId) {
    console.log('📝 Creating new admin user with organization via direct DB calls...');
    await createUserWithOrgAndState(authFile, {
      email,
      password,
      fullName,
      orgName,
      orgDescription: 'E2E Testing Organization',
      groupRole: 'admin',
    });
    console.log('✅ Created admin user, organization, and saved auth state');
    return;
  }

  // Scenario 2: User exists but no org - create org
  if (!orgId) {
    console.log('🏢 Creating organization for existing user via direct DB calls...');

    // Create organization
    const org = await createTestOrganization({
      name: orgName,
      description: 'E2E Testing Organization',
      ownerId: userId,
    });
    orgId = org.id;

    // Add user to organization
    await addUserToOrganization(orgId, userId);

    // Create default admin group
    const group = await createTestGroup({
      orgId,
      role: 'admin',
    });

    // Add user to group
    await addUserToGroup(group.id, userId, orgId);

    console.log(`✅ Created organization (ID: ${orgId})`);
  }

  // Scenario 3: User and org exist - just sign in and save state
  console.log('🔑 Signing in existing user and saving auth state...');
  const session = await signInUser(email, password);
  await savePlaywrightAuthState(session, authFile);
  console.log(`✅ Saved auth state to ${authFile}\n`);
});
