import { test as teardown } from '@playwright/test';
import { cleanupAllTestUsers } from './utils/test-cleanup';

/**
 * Global teardown that runs once after all tests.
 * Cleans up all test data to ensure a clean state for the next test run.
 *
 * This cleanup:
 * - Deletes all users matching the test email pattern
 * - Preserves the admin user for future test runs
 * - Removes all associated data (orgs, groups, invites, conversations, etc.)
 * - Removes Supabase Auth users
 *
 * The cleanup is comprehensive and order-aware to respect foreign key constraints.
 */
teardown('cleanup all test data', async () => {
  const adminEmail = process.env.TEST_ADMIN_EMAIL || 'admin.test@example.com';

  console.log('\n🧹 Running global teardown - cleaning up all test data...');

  try {
    // Clean up all test users except the admin
    // The pattern 'test+%@test.com' matches all test emails generated by generateTestEmail()
    // Format: test+{title}.w{index}.{timestamp}.{randomId}@test.com
    const result = await cleanupAllTestUsers(
      'test+%@test.com',
      [adminEmail], // Preserve admin user for next run
      true // verbose
    );

    if (!result.success) {
      console.error('❌ Teardown had errors:', result.errors);
    } else {
      console.log('\n📊 Teardown Summary:');
      console.log(`  - Messages: ${result.deletedCounts.messages}`);
      console.log(`  - Conversations: ${result.deletedCounts.conversations}`);
      console.log(`  - Model mappings: ${result.deletedCounts.modelMaps}`);
      console.log(`  - Group mappings: ${result.deletedCounts.groupMaps}`);
      console.log(`  - Invites: ${result.deletedCounts.invites}`);
      console.log(`  - Groups: ${result.deletedCounts.groups}`);
      console.log(`  - Models: ${result.deletedCounts.models}`);
      console.log(`  - Org mappings: ${result.deletedCounts.orgMaps}`);
      console.log(`  - Temp org requests: ${result.deletedCounts.tempOrgRequests}`);
      console.log(`  - Profiles: ${result.deletedCounts.profiles}`);
      console.log(`  - Organizations: ${result.deletedCounts.organizations}`);
      console.log(`  - Auth users: ${result.deletedCounts.authUsers}`);
    }
  } catch (error) {
    console.error('❌ Global teardown failed:', error);
    throw error;
  }

  console.log('\n✅ Global teardown complete!\n');
});
